name: Build Linux Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build package with Nix
        run: nix build .#packages.x86_64-linux.default

      - name: Resolve symlink and find ZIP file
        id: find_zip
        run: |
          REAL_PATH=$(readlink -f result)  # Resolve the symlink
          echo "Resolved path: $REAL_PATH"
          
          ZIP_FILE=$(find "$REAL_PATH/bin/linux-release" -maxdepth 1 -type f -name "*.zip" | head -n 1)
          
          if [[ -z "$ZIP_FILE" ]]; then
            echo "Error: No zip file found in $REAL_PATH/linux-release"
            exit 1
          fi
          
          echo "linux_release_zip_file=$ZIP_FILE" >> "$GITHUB_ENV"

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: ${{ env.linux_release_zip_file }}
          if-no-files-found: error
          retention-days: 14
